changesetBaseRefs:
  - main
  - origin/main
  - upstream/main

enableGlobalCache: false

nmMode: hardlinks-local

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - current
  os:
    - current
  libc:
    - current

yarnPath: .yarn/releases/yarn-4.0.0-rc.46.cjs
